services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - REDIS_ADDR=redis:6379
      - PORT=3002
    depends_on:
      - redis
    networks:
      - bespin-network

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=8000
      - NUXT_PUBLIC_API_URL=http://localhost:3002
    volumes:
      - ./web:/app
      - /app/node_modules
    depends_on:
      - api
    networks:
      - bespin-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - bespin-network
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  bespin-network:
    driver: bridge

volumes:
  redis-data:
